[package]
name = "zork"
version = "0.1.0"
authors = ["Phlosioneer <mattmdrr2@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
build-helper = "0.1"
pkg-config = "0.3"

